# Generated by Django 5.2.7 on 2025-10-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
