# Generated by Django 5.2.7 on 2025-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_title_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetversion',
            name='version_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
