# Generated by Django 5.2.7 on 2025-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetversion_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='assets/pictures/'),
        ),
    ]
