# Generated by Django 5.2.7 on 2025-10-10 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='assets/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('3d_model', '3D Model'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_extension', models.CharField(max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='assets.tag')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('file', models.FileField(upload_to='versions/%Y/%m/%d/')),
                ('changes', models.TextField(help_text='Description of changes made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Version',
                'verbose_name_plural': 'Asset Versions',
                'ordering': ['-version'],
                'unique_together': {('asset', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Metadata Field',
                'verbose_name_plural': 'Metadata Fields',
                'ordering': ['key'],
                'unique_together': {('asset', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['file_type', 'status'], name='assets_asse_file_ty_97aa75_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_at'], name='assets_asse_created_6d1779_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploaded_by'], name='assets_asse_uploade_7823da_idx'),
        ),
    ]
