# Generated by Django 5.2.7 on 2025-10-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('3d_model', '3D Model'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='changes',
            field=models.TextField(help_text='Description of changes made'),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='version',
            field=models.IntegerField(),
        ),
    ]
