# Generated by Django 5.2.7 on 2025-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('3d_model', '3D Model'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
