# Generated by Django 5.2.7 on 2025-10-20 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, help_text='Category, e.g., Marketing', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='technical_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Automatically extracted technical metadata'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='assets_asse_categor_f3ee6a_idx'),
        ),
    ]
