# Generated by Django 5.2.7 on 2025-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_category_asset_metadata_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='version_tags', to='assets.tag'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
