# Generated by Django 5.2.7 on 2025-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetversion_description_assetversion_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetversion',
            name='tags',
        ),
        migrations.AddField(
            model_name='assetversion',
            name='tags_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
